/control/verbose 2
/tracking/verbose 2

/histo/fileName Air.root

/det/detector/Number 21
/det/collimator/Number 21

/det/target/diameter 10 cm
/det/target/rotateAngle 0 deg
/det/target/position 0 0 0 cm

/gen/particle gamma
/gen/particle/energy 50 keV
/gen/particle/momentumDirection 0 90 0 deg
/gen/particle/deltaThetaPhi 0 0.5 40 deg

/gen/particle/position -24 0 0 cm

/run/initialize
/run/beamOn 50000
